### ISSUE TITLE
xdebug

### ISSUE THREAD

**Issue by wellic** [romeOz/docker-apache-php#1]
Are you going to add xdebug again?

**Comment by romeOz** [comment]
I wanted to minimize size a container. All the same xdebug is disigned for the development/test environment. You can use one of two choices to install the required php-extensions:
1. `docker exec -it app bash -c 'apt-get update && apt-get install -y php5-xdebug && rm -rf /var/lib/apt/lists/*'`
2. Create your container on based the current

Сontents Dockerfile:

``` bash
FROM romeoz/docker-apache-php:5.6

RUN apt-get update \
    && apt-get install -y php5-xdebug \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /var/www/app/

EXPOSE 80 433

CMD ["/sbin/entrypoint.sh"]
```

Next step,

``` bash
docker build -t php-5.6 .
docker run --name app -d -p 8080:80 php-5.6
```

**Comment by wellic** [comment]
Thank you for your helpful answer.
