### ISSUE TITLE
Out of the Box www location

### ISSUE THREAD

**Issue by Hi-ImKyle** [romeOz/docker-apache-php#3]
Ok so I'm still getting the hang of how docker works and what not since I've moved most of my programs without issue over to it. Just I can't for the life of me find where the www is for this container?

Can you help me please?

**Comment by romeOz** [comment]
If source code is on a host, then:
```
docker run --name app -d -p 8080:80 \
   -v /host/to/path_source_code/:/var/www/app/ \
   romeoz/docker-apache-php
```
tip from [README](https://github.com/romeOz/docker-apache-php#developmentpersistence)

But right way is source code and environment (in this case, Apache and php) must be inside docker-image. Development, unit-testing and deploy of code is made within environment, i.e. such a image moves throughout the chain step by step.

For this create your image on based current.

Сontents Dockerfile:
```
FROM romeoz/docker-apache-php:7.3

COPY /host/to/path_source_code/ /var/www/app/

WORKDIR /var/www/app/

EXPOSE 80 443

CMD ["/sbin/entrypoint.sh"]
```
Next step,
```
docker build -t php-7.3 .
docker run --name app -d -p 8080:80 php-7.3
```
Docks on command [COPY](https://docs.docker.com/engine/reference/builder/#copy)

So, each project should have its own image.
